version: '3.2'

services:
  calculator:
    container_name: calculator
    image: devopsdockeruh/scaling-exercise-calculator
    ports:
      - 3000:3000
  compute:
    image: devopsdockeruh/scaling-exercise-compute
    environment:
      - VIRTUAL_HOST=compute.localtest.me
  load-balancer:
    container_name: load-balancer
    build: ./scaling-exercise/load-balancer
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
